# Generated by Django 2.1.7 on 2019-03-14 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Subject Name')),
                ('code', models.CharField(max_length=50, verbose_name='Subject Code')),
                ('theory', models.BooleanField(default=True)),
                ('elective', models.BooleanField(default=False)),
                ('project', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.CharField(max_length=50, verbose_name="Student's Section")),
                ('batch', models.CharField(blank=True, max_length=50, null=True, verbose_name="Student's Batch")),
                ('sub_batch', models.CharField(blank=True, max_length=50, null=True, verbose_name="Student's sub batch")),
                ('ug', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Student Count')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type of User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lab Batch'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_joining',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='held_designation_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='industry_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='partially_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='research_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lab Sub Batch'),
        ),
        migrations.AddField(
            model_name='user',
            name='teaching_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teaches',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', to='users.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form', to='users.Designation'),
        ),
        migrations.AddField(
            model_name='user',
            name='elective',
            field=models.ManyToManyField(blank=True, null=True, to='users.Subject'),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Semester'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ManyToManyField(to='users.UserType'),
        ),
    ]
